### ISSUE TITLE
Likely issue with rails 6.1.0-alpha

### ISSUE THREAD

**Issue by josh-m-sharpe** [romanbsd/heroku-deflater#54]
Using rails 00c2d3e1e61093451a00b1b70548cfd9ae549c53 as of this writing.

```
2020-06-13T18:37:54+00:00: Rack app error handling request { GET /assets/admin-c9569c117d1107474494012b3a255f49a3570eedd08e51123008d0412abc93cb.js }
#<NoMethodError: undefined method `match?' for #<ActionDispatch::FileHandler:0x000055dc97100c10>>
/app/vendor/bundle/ruby/2.6.0/gems/heroku-deflater-0.6.3/lib/heroku-deflater/serve_zipped_assets.rb:31:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-c13d46937445/actionpack/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
```

I'd guess this is related to [this commit](https://github.com/rails/rails/commit/e3ef5911a195e460bfa456f9c75e1abe4041d036#diff-6897a0b59abaaa3bbc85da93757c39d9L30), which not only removes the `match?` method - it does away with `FileHandler` in favor of `Static`

**Comment by sedubois** [comment]
I also got this issue when upgrading my Rails app to 6.1.0.rc1:

```rb
2020-11-04 16:26:31 +0100 Rack app ("GET /assets/application-d202e7f926ea26f1a77ad108db4187a078d7c86bebf0e97e4fe24242cdc9c487.css" - (127.0.0.1)): #<NoMethodError: undefined method `match?' for #<ActionDispatch::FileHandler:0x00007f9009c58d48>>
2020-11-04 16:26:31 +0100 Rack app ("GET /assets/application-3e190496dea178b3bbd482d5809118b541c5a13462d8fccbe725158cbeac7d92.js" - (127.0.0.1)): #<NoMethodError: undefined method `match?' for #<ActionDispatch::FileHandler:0x00007f9009c58d48>>
...
```

CSS/JS assets can't load so the system tests generate screenshots with only HTML and no styling applied. I also get errors such as `error: ReferenceError: $ is not defined` because of this. I did not notice the issue when running the app in development because I load this gem as follows: `gem 'heroku-deflater', group: [:production, :test]`.

However I believe my app actually does not need this. I'm not sure which one does the job, but between the app being deployed on Heroku and having CloudFlare in front of this, I checked that when I remove this gem `heroku-deflater`, deploy to production, and check the traffic with the browser dev tools, there is still a response header `content-encoding: br`. Also, my vague understanding is that if compression needed to be done within Rails, it could be achieved by adding `config.middleware.insert_after ActionDispatch::Static, Rack::Deflater` to `config/application.rb`. I would just have liked to have a way to test to guarantee that compression is happening, something I could do before when using this gem (I had written a test taking inspiration from [this post](https://thoughtbot.com/blog/content-compression-with-rack-deflater)).

**Comment by atstockland** [comment]
I am experiencing this issue with Rails 6.1 on heroku.

**Comment by janklimo** [comment]
@romanbsd this gem has been very helpful for years, thank you for your work on it. Question: given [these updates](https://github.com/rails/rails/commit/e3ef5911a195e460bfa456f9c75e1abe4041d036) would you say the scope of this gem is supported by Rails natively as of 6.1? If so, we might just update the readme.

**Comment by romanbsd** [comment]
I don't have time to support this at the moment, but I'll be happy to receive a PR.

**Comment by pungerfreak** [comment]
If I'm understanding this correctly, the functionality provided by the class `ServeZippedAssets` is now built into `ActionDispatch::Static`. It seems probable that has been the case for some time, but since nothing was breaking we never noticed it.

@romanbsd introduced this feature in 2013, [here](https://github.com/romanbsd/heroku-deflater/blob/947c1805ef07448c0a0761ccbdca711d699eae79/lib/heroku-deflater/serve_zipped_assets.rb), and Rails introduced [this](https://github.com/rails/rails/blob/v4.2.0.beta2/actionpack/lib/action_dispatch/middleware/static.rb) in 2014 and then improved it over the years to offer much of the same abilities as @romanbsd baked into his. But the recent refactor of that class removed the interface this gem expected. To maintain expected behavior, it seems like a simple major/minor version check could be added and bypass this in the case of Rails 6.1+.

I'll gladly put together a PR if I'm on the right track.

ps - It seems there may be other aspects of this gem that are baked into Rails now, but I don't have time to dig through.

**Comment by JunichiIto** [comment]
I got the same error, but I found I should have changed the setting below:

```diff
 # config/application.rb
-config.load_defaults 6.0
+config.load_defaults 6.1
```

I could solve the issue with this change.

**Comment by xxx** [comment]
Could someone please clarify if this gem is useful for Rails 6.1?

We're also in a state where removing the gem makes our app work after upgrading to 6.1, but I'm trying to figure out if I should continue to follow this gem, or if it's obsolete.

**Comment by mtmail** [comment]
On our website with Rails 6.1 it became obsolete. We removed it. And added `config.middleware.use Rack::Deflater` in `config/application.rb` instead.

**Comment by jsaraiva** [comment]
I also removed it, and replaced it with:
`
config.middleware.use Rack::Deflater,
  include: Rack::Mime::MIME_TYPES.select{|k, v| v =~ /text|json|javascript/ }.values.uniq,
  if: lambda {|env, status, headers, body| body.body.length > 512 }

require 'rack/brotli'

config.middleware.use Rack::Brotli,
  include: Rack::Mime::MIME_TYPES.select{|k, v| v =~ /text|json|javascript/ }.values.uniq,
  if: lambda {|env, status, headers, body| body.body.length > 512 },
  deflater: {
    quality: 1
  }
`
at the end of application.rb. Note that the Brotli middleware requires the rack-brotli gem.

This encodes javascript, css, and html with Brotli (if supported as per the request's Accepts header), or GZip otherwise.

**Comment by jjb** [comment]
other discussion: https://github.com/romanbsd/heroku-deflater/issues/32 https://github.com/romanbsd/heroku-deflater/issues/37
